### PR TITLE
Fully delete plan

### LINKED ISSUE #160: Deleting a plan from the planner causes a LoadObject error
Image

Steps to reproduce:

1. Make a new plan or target an existing plan
2. Edit the plan and then delete it
3. Notice the error in the console. The deletion happens successfully, but there is a problem with state.

### PR DESCRIPTION
**Pull request by barneyb**
When creating/deleting a plan, refetch the "all plans" query. When deleting, evict the deleted plan. When selecting a plan - including implicitly due to the active plan having disappeared - ensure the URL gets updated to match. This last closes #160.

### CODE REVIEW

File: src/features/Planner/data/utils.ts [hunk 1]
```diff
@@ -146,6 +147,7 @@ export const selectList = (state, id) => {
         state = addTask(state, id, "");
     }
     PlanApi.getDescendantsAsList(state.activeListId);
+    history.push(`/plan/${id}`);
```
Comment (barneyb) [inline src/features/Planner/data/utils.ts:150]: @switzerb this is the magic line. Without it, the now-deleted plan is reselected via the route match: GONK!

Comment (switzerb) [reply src/features/Planner/data/utils.ts:150]: wow -- i would not have predicted that. nice find!
